### DISCUSSION TITLE
best way to set configuration values from Home Assistant

### DISCUSSION THREAD

**Discussion by scruysberghs** [davidusb-geek/emhass#400] [General]
Now that all emhass config settings can be passed at runtime I was thinking about the best way to expose those settings in Home Assistant to be set in automations, input select or input sliders. I now use a package yaml file and a script/automations to pass them all as runtime parameters to day_ahead and mpc rest call's. This is possible but left me thinking if it would be a better idea to just expose all emhass settings in Home Assistant from the add-on, including a HA dashboard with all the entities and graphs. Or if that is not possible from the add-on, from an emhass "integration"? 
Just wanted to hear other people's opinion how they see the way forward towards a more userfriendly emhass before spending more time on my package file.

Some portions of the emhass.yaml package file I use now :
```
# ----------------------
# INPUT boolean
# ----------------------
input_boolean:
  ## Battery Settings
  pac_set_battery_dynamic:
    name: "Enable Dynamic Battery Control"
    icon: mdi:battery-charging-wireless

  pac_set_nocharge_from_grid:
    name: "Disable Charging from Grid"
    icon: mdi:power-off
...
...
...
# -----------------------
# INPUT NUMBER
# -----------------------
input_number:
  pac_maximum_power_to_grid:
    name: "Maximum Power to Grid"
    min: 0
    max: 10000
    step: 500
    unit_of_measurement: W
    initial: 5000
## Battery Settings
  pac_weight_battery_discharge:
    name: "cost weight for battery discharge"
    min: 0.0
    max: 1.0
    step: 0.01
    unit_of_measurement: "EUR/kWh"
    initial: 0.05
...
...
...
# ----------------------
# INPUT SELECTS
# -----------------------
input_select:
  pac_costfun:
    name: "Optimization Cost Function"
    options:
      - profit
      - cost
      - other
    initial: profit
...
...
...
automations and scripts to map the parameters to the payload template to use in the rest calls
...
...
...
# --------------------------
# REST COMMANDS
# --------------------------
rest_command:
  emhass_rest_daily_api:
    url: "http://localhost:5000/action/dayahead-optim"
    method: post
    content_type: "application/json"
    timeout: 120
    payload: "{{ payload }}"
    headers:
      Content-Type: application/json
...
....
```

**Comment by davidusb-geek** [comment]
Hi, it would be nice to hear what people think about this.
I don't what is the best/easiest option. But input boolean, numbers and selects seems fine enough to me, but it requires some effort to setup.
You were thinking about something directly exposed in the EMHASS webui? Because that will need even more development.
Maybe the best tradeoff is what you have already done but develop a blueprint that anyone can easily copy and use.

**Comment by scruysberghs** [comment]
For deferable loads  I now use a package file per deferable load. 
emhass_def0.yaml ... emhass_def3.yaml , see below(sorry, descriptions are in Dutch) 
```
# ------
# INPUTS
# ------
input_text:
  deferrable0_name:
    name: Naam apparaat
    icon: mdi:label
    mode: text

input_number:
  deferrable0_nominal_power:
    name: Nominaal vermogen (W)
    min: 0
    max: 10000
    step: 100
    icon: mdi:lightning-bolt
  deferrable0_operating_hours:
    name: Bedrijfsuren (uren)
    min: 0
    max: 24
    step: 1
    icon: mdi:clock
  deferrable0_start_timestep:
    name: Starttijd (stap)
    min: 0
    max: 48
    step: 1
    icon: mdi:timer-outline
  deferrable0_end_timestep:
    name: Eindtijd (stap)
    min: 0
    max: 48
    step: 1
    icon: mdi:timer-off-outline
  deferrable0_startup_penalty:
    name: Opstartboete
    min: 0
    max: 1000
    step: 10
    icon: mdi:alert-circle-outline

input_boolean:
  deferrable0_current_state:
    name: Apparaat actief?
    icon: mdi:power
  deferrable0_semi_cont:
    name: Semi-continue belasting?
    icon: mdi:toggle-switch
  deferrable0_single_constant:
    name: Constante belasting?
    icon: mdi:toggle-switch
```
In the frontend it then looks like this:
![image](https://github.com/user-attachments/assets/74a40ee8-72df-4159-b93c-b763ef6dd025)

In the rest call template i now have:
```
"num_def_loads": 4,
              {% set loads = [0, 1, 2, 3] %}
              {% set op_hours = loads | map('string') | map('regex_replace', '^', 'input_number.deferrable') | map('regex_replace', '$', '_operating_hours') | map('states') | map('int') | list %}
              {% set current_states = loads | map('string') | map('regex_replace', '^', 'input_boolean.deferrable') | map('regex_replace', '$', '_current_state') | map('states') | map('replace', 'on', 'true') | map('replace', 'off', 'false') %}
              {% set nominal_powers = loads | map('string') | map('regex_replace', '^', 'input_number.deferrable') | map('regex_replace', '$', '_nominal_power') | map('states') | map('float') | list %}
              {% set start_timesteps = loads | map('string') | map('regex_replace', '^', 'input_number.deferrable') | map('regex_replace', '$', '_start_timestep') | map('states') | map('int') | list %}
              {% set end_timesteps = loads | map('string') | map('regex_replace', '^', 'input_number.deferrable') | map('regex_replace', '$', '_end_timestep') | map('states') | map('int') | list %}
              {% set semi_cont = loads | map('string') | map('regex_replace', '^', 'input_boolean.deferrable') | map('regex_replace', '$', '_semi_cont') | map('states') | map('replace', 'on', 'true') | map('replace', 'off', 'false') %}
              {% set single_constant = loads | map('string') | map('regex_replace', '^', 'input_boolean.deferrable') | map('regex_replace', '$', '_single_constant') | map('states') | map('replace', 'on', 'true') | map('replace', 'off', 'false') %}
              {% set startup_penalty = loads | map('string') | map('regex_replace', '^', 'input_number.deferrable') | map('regex_replace', '$', '_startup_penalty') | map('states') | map('int') | list %}
                "operating_hours_of_each_deferrable_load": {{ op_hours }},
                "def_current_state": [{{ current_states | join(', ') }}],
                "nominal_power_of_deferrable_loads": {{ nominal_powers }},
                "start_timesteps_of_each_deferrable_load": {{ start_timesteps }},
                "end_timesteps_of_each_deferrable_load": {{ end_timesteps }},
                "treat_deferrable_load_as_semi_cont": [{{ semi_cont | join(', ') }}],
                "set_deferrable_load_single_constant": [{{ single_constant | join(', ') }}],
                "set_deferrable_startup_penalty": {{ startup_penalty }},

```

This means the number of deferable loads is now fixed and set to 4 but you can set the parameters to 0 to not have them planned.

This is only the deferable load part. I have done the same with a package file for battery parameters etc. I guess indeed package files in combination with blueprints could make for a low(er) level entry to setup.

The name labels I set for the deferable loads can be used in apexcharts.

![image](https://github.com/user-attachments/assets/373615e4-6a7f-4990-becb-e2d91d3a4410)
