### ISSUE TITLE
FR: Return forecast values to home assistant sensor entity attributes

### ISSUE THREAD

**Issue by purcell-lab** [davidusb-geek/emhass#7]
A feature request.

The forecast values are currently written to the .csv file within the file system, but are unable to be accessed by home assistant.

Would it be possible to include the forecasts as attributes of the sensor entities published to home assistant.

This would enable the creation of the same chart of values as the web UI, but in Lovelace using the [apexcharts-card](https://github.com/RomRider/apexcharts-card)

For example the SolCast integration posts forecast PV through a series of sensors and attributes.
![image](https://user-images.githubusercontent.com/79175134/169063174-2e2b5c00-8649-46cf-9ac2-2ae7c43d6713.png)

My energy provider also provides future price forecasts in entity attributes:
![image](https://user-images.githubusercontent.com/79175134/169063565-5d90a2ae-6763-4cc2-8103-186be96d8964.png)

When visualized in apexcharts looks like this:
![image](https://user-images.githubusercontent.com/79175134/169066690-4ac42151-2f2b-4c9e-a912-1d90826c4864.png)

**Comment by davidusb-geek** [comment]
Hi, I just published a new version where this was added. Test it to see if it fits your needs.

**Comment by davidusb-geek** [comment]
I tried this block of code:

```
            forecast_list = copy.deepcopy(data_df).loc[data_df.index[idx]:].reset_index()
            forecast_list.columns = ['timestamps', entity_id]
            ts_list = [str(i) for i in forecast_list['timestamps'].tolist()]
            vals_list = [np.round(i) for i in forecast_list[entity_id].tolist()]
            forecast_list = [{'timestamp': ts_list[i], entity_id.split('sensor.')[1]: vals_list[i]} for i in range(len(ts_list))]
```

But this is the result, not quite what a typical forecast sensor shows:
![image](https://user-images.githubusercontent.com/32926550/169394147-85e43e25-f874-4ba9-a348-b50cc452800d.png)

**Comment by davidusb-geek** [comment]
Ok just found how they are doing it in Amber: https://github.com/home-assistant/core/blob/dev/homeassistant/components/amberelectric/sensor.py

I will update that for the next release...

**Comment by purcell-lab** [comment]
Great, I can see the values there now, so can do something with them.  

I would be good if you can get into a similar structure as amber integration as that is quite easy to work with using map(attribute):

```yaml
post_mpc_optim: "curl -i -H \"Content-Type: application/json\" -X POST -d '{\"prod_price_forecast\":{{(
          (state_attr('sensor.amber_feed_in_forecast', 'forecasts')|map(attribute='per_kwh')|list)) 
          }},\"load_cost_forecast\":{{(
          (state_attr('sensor.amber_general_forecast', 'forecasts') |map(attribute='per_kwh')|list))
          }},\"prediction_horizon\":{{(
          (state_attr('sensor.amber_feed_in_forecast', 'forecasts')|map(attribute='per_kwh')|list|length)) 
          }},\"soc_init\":{{states('sensor.powerwall_charge')|float(0)/100}},\"soc_final\":0.01,\"def_total_hours\":[4,5,3,1]}' http://localhost:5000/action/naive-mpc-optim"
```

```
post_mpc_optim: "curl -i -H \"Content-Type: application/json\" -X POST -d '{\"prod_price_forecast\":[0.28, 0.33, 0.37, 0.32, 0.31, 0.31, 0.28, 0.27, 0.37, 0.46, 0.46, 0.46, 0.46, 0.46, 0.33, 0.33, 0.46, 0.46, 0.46, 0.37, 0.33, 0.33, 0.32, 0.3, 0.3, 0.31, 0.46, 0.33, 0.31, 0.3, 0.31, 0.3, 0.31, 0.3, 0.3, 0.26, 0.26, 0.26],\"load_cost_forecast\":[0.4, 0.45, 0.51, 0.45, 0.44, 0.44, 0.4, 0.4, 0.51, 0.61, 0.61, 0.61, 0.61, 0.61, 0.46, 0.46, 0.6, 0.61, 0.61, 0.5, 0.46, 0.45, 0.45, 0.43, 0.43, 0.44, 0.61, 0.46, 0.44, 0.42, 0.44, 0.42, 0.43, 0.43, 0.42, 0.38, 0.38, 0.38],\"prediction_horizon\":38,\"soc_init\":0.85,\"soc_final\":0.01,\"def_total_hours\":[4,5,3,1]}' http://localhost:5000/action/naive-mpc-optim"

**Comment by davidusb-geek** [comment]
Yes I will update this for the next release. That's a nice implementation of the shell command using templates and mapping the attributes. Do you mind if I borrow your code to put it as an example in the docs? It could help people with similar integrations.

A side comment on the values that you're passing for `soc_final` and `def_total_hours`. For the SOC if you do this at each iteration of the MPC it will always look to empty the battery. I think that you may lose optimality doing this. An idea could be to run the dayahead optimization  just once at the beginning of a new day and set the battery optimal power and SOC trajectories for the day. Then launch the MPC iteratively at a relative high frequency (10min?) and fix that final SOC to match the optimal trajectory for whole day computed with the dayahead optimization. The MPC will still let you optimize your system on short term uncertainties, but you will keep an optimal goal for your complete day. As for the `def_total_hours` what I'm doing is that I defined sensors for my deferrable loads that give me the current time in hours that those loads have done on the current day. So that when I perform the MPC optimization I'm passing the difference of the daily goal and the total hours ran for each deferrable load. Be careful because it doesn't make much sense to keep  `def_total_hours` at fixed values as shown in your code snippet.

Below is the code I use to compute running hours sensor for one of my deferrable loads, the water heater:

```
  - platform: history_stats
    name: Water Heater running today
    entity_id: sensor.water_heater_status
    state: 'Running'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: template
    sensors:
      water_heater_status:
        value_template: '{% if is_state("switch.water_heater_switch", "on") %}Running{% else %}Stopped{% endif %}'
        friendly_name: 'Water Heater Status'
        icon_template: mdi:play-pause
      water_heater_time_on:
        value_template: '{{ states("sensor.water_heater_running_today") | float }}'
        friendly_name: 'Water Heater Hours Running'
        icon_template: mdi:timer
```
