### ISSUE TITLE
Feature Request: smooth allocation of power to continuous loads

### ISSUE THREAD

**Issue by purcell-lab** [davidusb-geek/emhass#71]
I have three continuous loads in my configuration.

P_deferrable2 (EV charger) can take values between 0W to + 11 kW
P_deferrable3 (HVAC) can take values between 0W to 4 kW
P_batt which can take values from -15 kW to + 15 kW

![Screenshot 2023-04-10 10 18 32](https://user-images.githubusercontent.com/79175134/230803596-1eaf4bc6-5d8f-41a7-84bd-0c65c097f8ec.png)

As you can see in the above graph, the allocation of power to these loads is very lumpy between time slots.

For example rather than having the EV charging; [21530,11500,2173,11500] could this be smoothed to [6831, 6831, 6831, 6831] so the same in aggregate?

Similar for battery charging currently [0, -15000, 0, -15000] could this be smoothed to [-7500, -7500, -7500, -7500]?

![Screenshot 2023-04-10 10 29 00](https://user-images.githubusercontent.com/79175134/230803944-ac19f3cb-368a-4210-8c58-db6fbcdff9a3.png)

The benefits of a smoothed allocation is all continuous loads receive an ongoing proportion rather than starting and stopping on alternative time slots (useful for battery and HVAC) and if things change, such as the EV departing, it will have received some power allocation earlier in the day.

**Comment by davidusb-geek** [comment]
This is a very important improvement for me but I just haven't been able to find the time to work on this lately. But it is in the to do list.

**Comment by davidusb-geek** [comment]
This is implemented in the latest release that I've just launched. It should be available soon.
I did some testing on this. The main thing is that it is hard to add additional constraints to the deferrable loads because there is a main power balance contraint. Adding new constraints to smooth the power then almost always resulted in infeasible conditions.
So what I did to solve this problem is just to add this dynamic constraint to the battery power. In my tests it seems to work very well to smooth both the battery power and the deferrable load power at the same time. But this still needs more testing on your side to see if its working as intended. I guess that this makes senses as this is why the battery is there for, to add a much desired flexibility right?
The downside is for people that don't have a battery (like me), where I just don't see it possible to add more contraints to the deferrable loads without affecting the LP feasibility.
Please test and give your feedback when possible.
Cheers

**Comment by purcell-lab** [comment]
Looking forward to testing.  Thanks.

**Comment by purcell-lab** [comment]
I am wondering if it is possible for a continuous load to also be defined as having just one startup (set_def_constant).

Deferrable3 - HVAC in this case is still starting and stopping, even with the battery smoothing.

If it could be constrained to have only one run window, then it should present a smoothed outcome, rather than starting and stopping.

Is this the correct payload to achieve this?

```yaml
        "num_def_loads": 6,
        "def_total_hours": {{[states('sensor.def_total_hours_pool_filter')|int(0),
                              states('sensor.def_total_hours_pool_heatpump')|int(0),
                              states('sensor.def_total_hours_ev')|int(0),
                              states('sensor.def_total_hours_hvac')|int(0),
                              states('sensor.def_total_hours_hws')|int(0),
                              states('input_number.car2_def_total_hours')|int(0)]}}
        "P_deferrable_nom": [1340, 5000, 11500, 4000, 600,11500],
        "treat_def_as_semi_cont": [1, 1, 0, 0, 1, 0],
        "set_def_constant":       [0, 0, 1, 1, 0, 1]
```

![image](https://github.com/davidusb-geek/emhass/assets/79175134/dd710987-bdd1-46fc-86e5-12d31b0b8c4c)
